version: '3.8'
services:
  db:
    build: .
    container_name: 'db' 
    restart: always
    environment: 
      TZ: Asia/Shanghai
    working_dir: /app
    volumes:
      - ./game_config:/app/game_config
      - ./service_config:/app/service_config
      - ./pids:/app/pids
      - ./proto:/app/proto
      - ./script:/app/script
      - ./logs:/app/logs
      - ./run.sh:/app/run.sh
    ports: 
      - "9000:9000"
      - "5001:5001"
    depends_on: 
      - redis
      - mysql
    command: ["/app/run.sh", "db"]
  login:
    build: .
    container_name: 'login' 
    restart: always
    environment: 
      TZ: Asia/Shanghai
    working_dir: /app
    volumes:
      - ./game_config:/app/game_config
      - ./service_config:/app/service_config
      - ./pids:/app/pids
      - ./proto:/app/proto
      - ./script:/app/script
      - ./logs:/app/logs
      - ./run.sh:/app/run.sh
    ports: 
      - "9001:9001"
      - "5000:5000"
      - "8101:8101"
    command: ["/app/run.sh", "login"]
  game0:
    build: .
    container_name: 'game0' 
    restart: always
    environment: 
      TZ: Asia/Shanghai
    working_dir: /app
    volumes:
      - ./game_config:/app/game_config
      - ./service_config:/app/service_config
      - ./pids:/app/pids
      - ./proto:/app/proto
      - ./script/game:/app/script/game
      - ./script/lualib:/app/script/lualib
      - ./script/service:/app/script/service
      - ./logs:/app/logs
      - ./run.sh:/app/run.sh
    ports: 
      - "9002:9002"
      - "5002:5002"
      - "8547:8547"
    command: ["/app/run.sh", "game0"]
  game1:
    build: .
    container_name: 'game1' 
    restart: always
    environment: 
      TZ: Asia/Shanghai
    working_dir: /app
    volumes:
      - ./game_config:/app/game_config
      - ./service_config:/app/service_config
      - ./pids:/app/pids
      - ./proto:/app/proto
      - ./script/game:/app/script/game
      - ./script/lualib:/app/script/lualib
      - ./script/service:/app/script/service
      - ./logs:/app/logs
      - ./run.sh:/app/run.sh
    ports: 
      - "9003:9003"
      - "5003:5003"
      - "8548:8548"
    command: ["/app/run.sh", "game1"]
  redis:
    image: redis:alpine 
    container_name: 'redis' 
    restart: always
    environment: 
      TZ: Asia/Shanghai
    volumes: 
      - ./redisdata:/data
    ports: 
      - "6379:6379" 
  mysql:
    image: mysql:5.7.31
    container_name: 'mysql'
    restart: always
    environment: 
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 712z0hyzRmbVOs5G
      MYSQL_DATABASE: skynet 
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports: 
      - "3306:3306"