version: '3.8'
services:
  game:
    build: .
    container_name: 'game' 
    restart: always
    environment: 
      TZ: Asia/Shanghai
    working_dir: /app
    volumes:
    - ./game_config:/app/game_config
    - ./service_config:/app/service_config
    - ./pids:/app/pids
    - ./proto:/app/proto
    - ./script/game:/app/script/game
    - ./script/lualib:/app/script/lualib
    - ./script/service:/app/script/service
    - ./logs:/app/logs
    - ./run.sh:/app/run.sh
    ports: 
      - "9002:9002"
      - "5002:5002"
      - "8547:8547"
    command: ["/app/run.sh", "game0"]
